### ISSUE TITLE
Correctly implement GetValue()

### ISSUE THREAD

**Issue by dirkjanfaber** [Chris927/dbus-victron-virtual#3]
See the difference between the following 2 commands (as also seen in #2):

```
root@ekrano:~# dbus -y com.victronenergy.temperature.ruuvi_dd4240ee1474 /DeviceInstance GetValue
value = 25
root@ekrano:~# dbus -y com.victronenergy.temperature.virtual_dfa /DeviceInstance GetValue
Traceback (most recent call last):
  File "/usr/bin/dbus", line 374, in <module>
    ret = obj.object.get_dbus_method(method.name, iface.name)(*args)
AttributeError: 'NoneType' object has no attribute 'name'
root@ekrano:~# 
```

**Comment by Chris927** [comment]
Hi @dirkjanfaber, `GetValue` should now be implemented, and this issue should be resolved.

You should be able to test as follows, using the [test project](https://github.com/Chris927/dbus-victron-virtual-test):

1. Do a fresh `git clone git@github.com:Chris927/dbus-victron-virtual-test.git`
2. `cd dbus-victron-virtual-test`
3. `npm install` (this will install the un-released version of dbus-victron-virtual)
4. run the test project: `DBUS_SESSION_BUS_ADDRESS=unix:socket=/var/run/dbus/system_bus_socket node index.js`
5. In a different terminal: `dbus -y -t com.victronenergy.my_service1 /RandValue GetValue`

The last command should give you output like this:

```bash
# dbus -y -t com.victronenergy.my_service1 /RandValue GetValue
value = 20
```

Do let me know if this test is positive, and if the issue is resolved in your environment, too.

**Comment by dirkjanfaber** [comment]
This works. Closing this issue.
