### ISSUE TITLE
Interface undefined is not supported

### ISSUE THREAD

**Issue by dirkjanfaber** [Chris927/dbus-victron-virtual#5]
Could very well be related to issue #4, but I do get the _Interface undefined is not supported_ message when running my branch.

Which comes from https://github.com/sidorares/dbus-native/blob/master/lib/bus.js#L172. Adding a bit more debbuging to it:
```
Interface undefined is not supported
unknown service: {
  serial: 6414,
  path: '/DeviceInstance',
  destination: 'com.victronenergy.temperature.virtual_dfa',
  member: 'GetValue',
  sender: ':1.31',
  type: 1,
  flags: 0
}
```

**Comment by Chris927** [comment]
This was fixed by [implementing the ability to call without an interface](https://github.com/sidorares/dbus-native/commit/0e6d9c1b88271f4b3d617df55f2bec26e9462e8d) in dbus-native. For this, I created [this fork](https://github.com/Chris927/dbus-native) of the package, which is available as `dbus-native-victron` on npmjs.com.
